### ISSUE TITLE
Concatenation for task states with different dimensions

### ISSUE THREAD

**Issue by sabeaussan** [general-robotics-duke/Policy-Stitching#1]
Hi,

Thank you for sharing your code. Looking at the script that generate the anchor points, it seems that we need to concatenate along the first dimension the task states of different tasks. However, these may have different size. What is the right way to accomodate ? Is padding the smallest size enough ?

**Comment by Pingcheng-Jian** [comment]
Hi,

Thanks for your interest for our paper. In our experiments, we tried the Policy Stitching between Push tasks and PickAndPlace tasks with different environment dynamics (such as friction, rough table terrain, etc.). These tasks all have the same task state dimension, since they all only involves the state of one object (such as a cube or a bar). The task state consists of the position, angle, positional and angular velocities, etc.

We have never tried Policy Stitching with different task state dimensions, and we are not sure what should be the right way for concatenation in this case, maybe zero padding the smallest size can work. Our experience is that when the tasks to transfer become drastically different, the zero-shot success rates usually become small. I think that is one of the limitations of this paper, and has been stated in the limitation section.

**Comment by sabeaussan** [comment]
Thank you for your answer. I was also wondering why you exclude eef information from the task observation ? `task_inputs = np.concatenate([obs[self.ee_dim:], g])`
Any reason for not providing it to the agent ?

**Comment by Pingcheng-Jian** [comment]
Yes, great question. We deliberately remove the eef information from the robot state and the task state, and only preserve the joint information such as joint angles and velocities. That is because we want the robot network module to implicitly learn the robot kinematics during the training, by giving it the joint state as input and asking it to output joint actions that can manipulate the target object. In order to manipulate the object, the robot module has to implicitly learns how the joint angles will affect the position of the end effector, which is exactly the robot kinematics.

We believe that is the basic logic of why we can disentagle the task module with the robot module and swap between different modules: we enforce each robot module to learn the specific robot kinematics.

On the other hand, if we include the robot eef information in the robot state or the task state, the robot module will probably learn to ignore the joint information, and only uses the eef information (or embedded eef information if given in the task state) and the embedded object information (from the task module) to decide where the end effector should move to in the next step. This information leak will give the robot network module a path to "cheat" and accomplish the task, without learning the real robot kinematics. If the robot module cannot implicitly learn the robot kinematics, the whole policy stitching process will not make any sense.
